### ISSUE TITLE
Doesn't work with notebook?

### ISSUE THREAD

**Issue by gitfoxi** [joferkington/mpldatacursor#12]
Trying this for the first time. It's a cool idea. I can confirm that it crashes with the osx backend. That backend is hella sketchy anyway. I tried it with the ipython notebook backend and it just doesn't seem to have any effect there unless I'm doing it wrong ...

**Comment by joferkington** [comment]
Just as a side-note, things do (mostly) work in IPython notebooks with the `nbagg` backend.  You'll need to explicitly use the backend through either:

    import matplotlib
    matplotlib.use('nbagg')
    import matplotlib.pyplot as plt

or with the IPython magic command `%matplotlib nbagg` on the latest version of IPython.

However, the performance is significantly lower than with desktop backends, so you may find hover mode, etc, rather laggy.

**Comment by chan-y-park** [comment]
Hi, I've been a happy user of mpldatacursor, and I was trying to run the same code, which I had no problem when I run it from a console, from an IPython notebook with the magic command ```%matplotlib nbagg```, but it does not work. 

For example, I used Firefox and the first example of ```README.md``` with the magic command, and mpldatacursor does not work. I am using Python 2.7.6 and IPython 3.2.0.

**Comment by joferkington** [comment]
Fixed in e398a8d22997150641da8464a20f1e8123f074d5.  The `nbagg` backend's timers are broken, so this is a workaround.  

Note to self: Submit a pull request upstream once I track down the issue in the nbagg backend.
