### ISSUE TITLE
twinx and datacursor

### ISSUE THREAD

**Issue by nilswagner** [joferkington/mpldatacursor#23]
How can I use the datacursor in case of a twinx statement ?

ax1  = fig.add_subplot(111)
ax2 = ax1.twinx()
ax1.plot(dv[:,1],sr[:,1],label=r'$f_1(x)$')
x = dv[:,1]
y = sr[:,1]
tck = splrep(x, y)
yp = splev(x,tck,der=1)
ax2.plot(x,yp,c='r',label=r'$\frac{\partial f_1}{\partial x}$')
ax1.set_ylabel(r'Fundamental eigenfrequency $f_1$ [Hz]')
ax1.set_xlabel(r'Position $x$')
ax1.grid()
ax2.set_ylabel('Sensitivity')
ax2.legend(loc=0)
c1=datacursor(axes=ax1,formatter='x={x:0.0f}\ny={y:0.2f}'.format,draggable=True,display="multiple")
c2=datacursor(axes=ax2,formatter='x={x:0.0f}\ny={y:0.2f}'.format,draggable=True,display="multiple")
plt.show()

**Comment by wilywampa** [comment]
Thanks for the very useful module.

The twin axes workaround only seems to work correctly if the two sets of axes have the same scale/limits, which sort of defeats the purpose:
![cursor](https://cloud.githubusercontent.com/assets/4472522/6771487/8746d590-d09c-11e4-8126-6041bec832eb.gif)

```python
import numpy as np
from mpldatacursor import datacursor

t = np.linspace(0, 10, 200)
x = np.cos(t)
y = np.sin(t)

plt.close('all')
f = plt.figure()
ax = f.gca()
ax.plot(t, 3 * x)
ax2 = ax.twinx()
ax2.plot(t, 10 * y, 'r')

cursor = datacursor(axes=f.get_axes(), hover=True)
```

matplotlib 1.4.3
mpldatacursor installed with pip via GitHub 5 days ago

**Comment by joferkington** [comment]
@wilywampa - Thanks for catching that! (and my apologies for my delay in replying)

I've pushed a fix for the problem.  Let me know if it does/doesn't work for you.

Thanks again for the bug report (and your other recent ones, as well)!

**Comment by wilywampa** [comment]
That fixed it. Thanks!
