### ISSUE TITLE
Better formatting

### ISSUE THREAD

**Issue by nilswagner** [joferkington/mpldatacursor#26]
Is it possible to obtain a better formatting like in \LaTex

\begin{eqnarray}
x_1 & = &  \ \
x_2 & = & 
\end{eqnarray}

import numpy as np
from scipy.optimize import  fmin_tnc, fmin_l_bfgs_b, fmin_cobyla
from numpy.random import randn
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import axes3d
from pylab import meshgrid
import matplotlib.cm as cm
from mpldatacursor import datacursor
plt.rc('text', usetex=True)
import matplotlib as mpl
mpl.rcParams['savefig.directory'] = ''
mpl.rcParams['savefig.dpi'] = 100

def f(x):

    return (4-2.1*x[0]**2+x[0]**4/3)*x[0]**2+x[0]*x[1]+(4*x[1]**2-4)*x[1]**2+x[0]+x[1]

def f1(x,y):

    return (4-2.1*x**2+x**4/3)*x**2+x*y+(4*y**2-4)*y**2+x+y

bounds = [[-2.,2.],[-2.,2.]]
x0 = randn(2)

x_opt, f_opt, d = fmin_l_bfgs_b(f,x0,fprime=None,approx_grad=1,bounds=bounds)
x_opt, nfeval, rc = fmin_tnc(f,x0,fprime=None,approx_grad=1,bounds=bounds)
print x_opt,f_opt

xi = np.linspace(-2,2,100)
yi = np.linspace(-2,2,100)

X, Y = meshgrid(xi, yi)
Z = f1(X,Y)

fig = plt.figure('Contour plot')
ax  = fig.add_subplot(111)
ax.contourf(X,Y,Z,20,alpha=0.25, cmap='jet')
C = ax.contour(X,Y,Z,20,colors='black',linewidth=.5)
ax.plot(x_opt[0],x_opt[1],'o')
#datacursor(formatter='x1 = {x:+0.5f}\n  x2 = {y:+0.5f}'.format,draggable=True,display="multiple")
datacursor(formatter=r'$x_1$ = {x:+0.5f}\\  $x_2$ = {y:+0.5f}'.format,draggable=True,display="multiple")
ax.set_title(r"$f(x_1,x_2)=(4-2.1\,x_1^2+\displaystyle \frac{x_1^4}{3})\,x_1^2+x_1\,x_2+(4\,x^2_2-4)\,x_2^2+x_1+x_2$")
ax.set_aspect('equal')
ax.set_xlabel(r'$x_1$')
ax.set_ylabel(r'$x_2$')
plt.show()

![contour_plot](https://cloud.githubusercontent.com/assets/5382885/3812145/2e84108e-1ca7-11e4-9b3d-980469e2386e.png)

**Comment by joferkington** [comment]
Hi Nils,

Sorry I never replied to this until now... It's not working, but in principle, it should work if `usetex=True`...  I'm not quite sure what's going on...
