### ISSUE TITLE
Cosmetic FancyArrow changes in matplotlib 1.4.x don't mix well with mpldatacursor's defaults

### ISSUE THREAD

**Issue by joferkington** [joferkington/mpldatacursor#30]
With matplotlib <1.4, FancyArrow's are clipped to the text's bbox:

![figure_1](https://cloud.githubusercontent.com/assets/906803/6314994/a4d17d9a-b9b8-11e4-99eb-83a9c2bc295c.png)

With matplotlib 1.4.0 and greater, the arrow extends to the center of the box:

![figure_1](https://cloud.githubusercontent.com/assets/906803/6314997/ca11baf2-b9b8-11e4-9e86-745eb8e618ec.png)

This may or may not be considered a bug, but I need a workaround before the next release of mpldatacursor.

**Comment by wilywampa** [comment]
If you create the datacursor with `draggable=True` then click and drag the box, the line is clipped as in your first image. Maybe that hints at a workaround?

**Comment by wilywampa** [comment]
Good news! This commit fixes the problem: https://github.com/efiring/matplotlib/commit/896880c0ae170a7ff6fab3243995d12c69bee70c found in this issue https://github.com/matplotlib/matplotlib/issues/4140. The bad news is it's not something you can fix in mpldatacursor until the next matplotlib release.

**Comment by joferkington** [comment]
@wilywampa - Yes, thanks for noticing the fix in matplotlib!  In the meantime, I'll probably just add a version conditional to default to a square annotation box on 1.4.x.

**Comment by joferkington** [comment]
Workaround added in a574ea580e076d50e243764a6d969e891a120057

**Comment by tacaswell** [comment]
This is also now fixed on master.
