### ISSUE TITLE
Problem with multiple draggable cursors

### ISSUE THREAD

**Issue by wilywampa** [joferkington/mpldatacursor#32]
Not sure how to describe this so I'll demonstrate with this:
![cursor2](https://cloud.githubusercontent.com/assets/4472522/6771558/aa87df16-d09e-11e4-9030-0fa2eaf303b3.gif)

For some reason there's a big discrepancy between where the mouse cursor actually is versus where the annotation thinks it is. Any idea what the problem is here?

```python
import numpy as np
from mpldatacursor import datacursor
import matplotlib.pyplot as plt

t = np.linspace(0, 10, 200)
x = np.cos(t)
y = np.sin(t)

plt.close('all')
plt.figure()
plt.plot(t, 3 * x)
plt.plot(t, 10 * y, 'r')

cursor = datacursor(axes=[plt.gca()], display='multiple', draggable=True)
```

**Comment by nilswagner** [comment]
Just out of curiosity, how did you record your desktop ?
Nils


Am 22.03.2015 um 22:23 schrieb wilywampa <notifications@github.com>:

**Comment by wilywampa** [comment]
LICEcap: https://github.com/lepht/licecap

**Comment by wilywampa** [comment]
This is a matplotlib issue: https://github.com/matplotlib/matplotlib/issues/4295
