### ISSUE TITLE
Feature: Make the default coordinate precision depend on the data density

### ISSUE THREAD

**Issue by jondo** [joferkington/mpldatacursor#33]
Currently, without the `formatter` argument, a default format of `0.3g` is used. It would be great to make this precision dependent on data density instead. This would make the default format much more useful.
It should not happen that two close data points get identical annotations by default.

**Comment by nilswagner** [comment]
+1

Nils

**Comment by joferkington** [comment]
Good point!  +1

I should have time to implement it this weekend (though if anyone wants to take a crack at it before then, feel free!).

I'm also overdue for a release.  Quite a few changes have accumulated since 0.3 was released.

**Comment by nilswagner** [comment]
Just out of curiosity will you fix this problem in the near future ?

**Comment by joferkington** [comment]
@nilswagner - Sorry for the delay on this!

Fixed in 768607d0218faf7e56525371c439a60bb3e0f40d
