### ISSUE TITLE
Right click doesn't close box

### ISSUE THREAD

**Issue by schlamar** [joferkington/mpldatacursor#35]
System: mpldatacursor 0.5, matplotlib 1.4.3, Windows 7, PyGTK backend

**Comment by joferkington** [comment]
First off, thanks for the bug reports!

Right-click to hide is only in the current git HEAD. It's not in v0.5.

I really should try to get a new release out soon.  That particular feature was added over a year ago, but I haven't made an official release in over a year.

If you have a chance, you might try installing from the current git version and see if that works.  I currently can't test on Windows with the GTK backend, so it's entirely possible that there could be a platform specific issue I'm missing.
