### ISSUE TITLE
Does not work reliable in step diagram

### ISSUE THREAD

**Issue by schlamar** [joferkington/mpldatacursor#36]
If I create a step diagram (randomly?) some areas do not work. Sometimes I click on the plot and nothing happens. Sometimes I select a point of from the plot and it gets selected.

**Comment by joferkington** [comment]
Thanks for reporting this and sorry I didn't reply earlier!

There's a partial fix in 0ef492ac496cabc9eb7ea823d390eb89032fb950.  However, there's an underlying bug in the way matplotlib detects whether a point is on a line in `Line2D.contains`.  Basically, it doesn't take into account a line's `drawstyle`.  (`plt.step` is actually `plt.plot(..., drawstyle='steps-pre')`.)

Note to self: Leaving this open as a reminder to file an MPL issue and a PR for a fix.

**Comment by tacaswell** [comment]
Yikes, that is a fun bug!

**Comment by anntzer** [comment]
Fixed upstream (matplotlib/matplotlib#6497).

**Comment by schlamar** [comment]
I assume this is fixed, but haven't confirmed it yet :)
