### ISSUE TITLE
No arrows with style ggplot

### ISSUE THREAD

**Issue by schlamar** [joferkington/mpldatacursor#37]
If I select the `ggplot` style with

    import matplotlib.style
    matplotlib.style.use('ggplot')

I get no arrows for the boxes:

![arrows_missing](https://cloud.githubusercontent.com/assets/238652/7392212/ac954c48-ee86-11e4-9010-3a1e1fa7f261.PNG)

**Comment by joferkington** [comment]
Thanks for the bug report and sorry for my delay in replying!

I've pushed a fix in cf65c681a87b97f20928366fcc67473fcfb3cf09.  In the meantime, you can work around this by specifying:

```
mpldatacursor.datacursor(arrowprops=dict(arrowstyle='->',
                                         connectionstyle='arc3,rad=0',
                                         edgecolor='black',
                                         facecolor='yellow'))
```


Thanks again for he bug report.
