### ISSUE TITLE
draggable annotation on image

### ISSUE THREAD

**Issue by feldman4** [joferkington/mpldatacursor#38]
Draggable box doesn't play well with imshow, unless the tooltip spawns outside the canvas.

```
import matplotlib.pyplot as plt
import numpy as np
from mpldatacursor import datacursor

data = np.outer(range(10), range(1, 5))

fig, ax = plt.subplots()
ax.set_title('Try dragging the annotation boxes')
ax.imshow(np.random.random(size=(100,100)), interpolation='nearest')

datacursor( draggable=True)

plt.show()
```

**Comment by joferkington** [comment]
@feldman4 - Thanks for the bug report! Sorry I've taken so long to reply.

It turns out this was a deeper issue with draggable datacursors and anything other than `display='multiple'`.

Should be fixed in 017db86a2ce04868e65e76de250c667224f2653d
