### ISSUE TITLE
PyQt backend: Cursor interaction should also work in pan or zoom mode

### ISSUE THREAD

**Issue by jondo** [joferkington/mpldatacursor#41]
I want to define data cursors (and move movable ones) even when the PyQt4 pan or zoom buttons are pressed. Currently, this is not possible.

I guess that this might not be implementable with the current state of the backend. Which backend changes would be needed? Will this work with the PyQt5 backend?

**Comment by joferkington** [comment]
There's no way to do this, as the matplotlib toolbar overrides the events passed in to `mpldatacursor`.  (If you think about it, how can matplotlib distinguish from a click to zoom and a click to pick with the datacursor?)

However, you can disable zoom/pan and go back to "normal" mode after you've zoomed to where you want.

By default, if you press the zoom/pan button again after zooming/panning, then `mpldatacursor` (and anything else connected to matplotlib events) will start to work again.

Hope that helps a bit, anyway.

**Comment by jondo** [comment]
> how can matplotlib distinguish from a click to zoom and a click to pick with the datacursor?

Zooming works by drawing a zoom window. This is a dragging operation, so single clicks could be passed through to mpldatacursor.

> However, you can disable zoom/pan and go back to "normal" mode after you've zoomed to where you want.

I know, but I recently had to manually annotate tens of graphs with datacursors, and all this mode changing became annoying after some time.

**Comment by tacaswell** [comment]
@jondo If you would like to look into this, there is some no-op catching code in the zoom logic which currently just snarfs the mouse event.  You could instead temporarily disable zoom, re-emit the event, and then re-enable zoom.  

I would be interested to see a PR implementing that in upstream matplotlib.
