### ISSUE TITLE
CGContext Ref is NULL

### ISSUE THREAD

**Issue by jlopezbi** [joferkington/mpldatacursor#42]
Hey There, 
just wanted to let you know about this error (Ipython error message below). This occurs when I enter the first example code from the readme, and then click on a line in the plot. I am a new user of matplotlib and scipy/numpy so my apologies if I am missing something trivial.
I am using python 2.7.8 matplotlib (1.4.3) and mpldatacursor (0.6.1)

cheers for putting this out there!

RuntimeError                              Traceback (most recent call last)
/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib/backend_bases.pyc in button_press_event(self, x, y, button, dblclick, guiEvent)
   1885         mouseevent = MouseEvent(s, self, x, y, button, self._key,
   1886                                 dblclick=dblclick, guiEvent=guiEvent)
-> 1887         self.callbacks.process(s, mouseevent)
   1888 
   1889     def button_release_event(self, x, y, button, guiEvent=None):

/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib/cbook.pyc in process(self, s, *args, **kwargs)
    538                     del self.callbacks[s][cid]
    539                 else:
--> 540                     proxy(*args, **kwargs)
    541 
    542 

/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib/cbook.pyc in __call__(self, *args, **kwargs)
    413             mtd = self.func
    414         # invoke the callable and return the result
--> 415         return mtd(*args, **kwargs)
    416 
    417     def __eq__(self, other):

/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/mpldatacursor/datacursor.pyc in _select(self, event)
    624                 new_event = PickEvent('pick_event', fig.canvas, fixed_event,
    625                                      artist, **info)
--> 626                 self(new_event)
    627 
    628         all_artists = itertools.chain(self.artists, self.annotations.values())

/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/mpldatacursor/datacursor.pyc in __call__(self, event)
    246                 pass
    247 
--> 248             self._show_annotation_box(event)
    249 
    250     def _event_ignored(self, event):

/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/mpldatacursor/datacursor.pyc in _show_annotation_box(self, event)
    286                 ann.set_visible(False)
    287 
--> 288         self.update(event, annotation)
    289 
    290     def event_info(self, event):

/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/mpldatacursor/datacursor.pyc in update(self, event, annotation)
    546 
    547         if self.keep_inside:
--> 548             self._keep_annotation_inside(annotation)
    549 
    550         event.canvas.draw()

/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/mpldatacursor/datacursor.pyc in _keep_annotation_inside(self, anno)
    554 
    555         # Need to draw the annotation to get the correct extent
--> 556         anno.draw(fig.canvas.renderer)
    557         bbox = anno.get_window_extent()
    558 

/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib/artist.pyc in draw_wrapper(artist, renderer, *args, **kwargs)
     57     def draw_wrapper(artist, renderer, *args, **kwargs):
     58         before(artist, renderer)
---> 59         draw(artist, renderer, *args, **kwargs)
     60         after(artist, renderer)
     61 

/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib/text.pyc in draw(self, renderer)
   2071             return
   2072 
-> 2073         self._update_position_xytext(renderer, xy_pixel)
   2074         self.update_bbox_position_size(renderer)
   2075 

/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib/text.pyc in _update_position_xytext(self, renderer, xy_pixel)
   1936         if self.arrowprops:
   1937             x0, y0 = xy_pixel
-> 1938             l, b, w, h = Text.get_window_extent(self, renderer).bounds
   1939             r = l + w
   1940             t = b + h

/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib/text.pyc in get_window_extent(self, renderer, dpi)
    796             raise RuntimeError('Cannot get window extent w/o renderer')
    797 
--> 798         bbox, info, descent = self._get_layout(self._renderer)
    799         x, y = self.get_position()
    800         x, y = self.get_transform().transform_point((x, y))

/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib/text.pyc in _get_layout(self, renderer)
    309         tmp, lp_h, lp_bl = renderer.get_text_width_height_descent('lp',
    310                                                          self._fontproperties,
--> 311                                                          ismath=False)
    312         offsety = (lp_h - lp_bl) * self._linespacing
    313 

/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib/backends/backend_macosx.pyc in get_text_width_height_descent(self, s, prop, ismath)
    164         size = self.points_to_pixels(points)
    165         width, height, descent = self.gc.get_text_width_height_descent(
--> 166             six.text_type(s), family, size, weight, style)
    167         return  width, height, 0.0*descent
    168 

RuntimeError: CGContextRef is NULL

**Comment by joferkington** [comment]
Thanks for the report!

At first glance, it looks like this is a bug in matplotlib's OSX backend. I'll look into it more soon.

What happens if you try using another backend?  For example, try running the following:

```
import matplotlib
matplotlib.use('TkAgg')
import matplotlib.pyplot as plt
from mpldatacursor import datacursor

fig, ax = plt.subplots()
ax.plot(range(10))
datacursor()
plt.show()
```

**Comment by tacaswell** [comment]
@mdehoon has method (currently merged to master) for getting around this issue for `tight_layout`.  I don't recall exactly how that code works so it might fix this as-is or provide a template for fixing this issue.

The underlying issue here is that on the Agg-based backends we can grab a graphics context and run a draw when every we want, where as in the OSX gui framework only lets you have a graphics context during it's draw callback when it is doing the actual re-draw for the screen.

**Comment by joferkington** [comment]
Ah, thanks for the explanation, Tom! I'll have a look at the tight layout
implementation.

**Comment by joferkington** [comment]
On a side note c678b127a0ddae3368cbacd8c75d20d5713671ac provides a workaround for this and an issue with the `NbAgg` backend.  However, I need to add a more complete fix, so I'm leaving this issue open as a reminder.

**Comment by great-thoughts** [comment]
Thanks for the neat package. I am trying to use it but  I get the exactly the same error described here. would appreciate any help.

**Comment by joferkington** [comment]
I've added a workaround for this issue in 1fad744. It fixes the issue on my test system, at any rate, though it's not an idea solution.  

On a side note, I really need to find an easier way to test the OSX backend... My current solution of firing up my old OSX install and trying to get a modern python environment working on it is starting to be more trouble than it's worth...

**Comment by tacaswell** [comment]
This is probably fixed in mpl master and 2.x.  The osx embedding now uses Agg to rasterize rather than doing the rendering via the OSX graphics API.
