### ISSUE TITLE
Display custom text or value upon hover

### ISSUE THREAD

**Issue by dnth** [joferkington/mpldatacursor#47]
Hi, I would like to display a custom text on my bar graph upon hovering over the bar. 
How can I achieve that?

**Comment by joferkington** [comment]
Hi @dnth,

To control the formatting of the string, use the `formatter` kwarg.  Have a look through the examples, and you'll see it used in several different places.  The documentation (i.e. `help(datacursor)` or in ipython `datacursor?`) has details on what keyword arguments are passed in.

As a general idea:

```
import numpy as np
import matplotlib.pyplot as plt
from mpldatacursor import datacursor

def formatter(**kwargs):
    height = kwargs['height']
    return "This bar is {:0.2f} units tall".format(height)

fig, ax = plt.subplots()
ax.bar(np.arange(5), np.random.random(5), color='lightblue')
ax.margins(0.05)
ax.set_ylim(bottom=0)
datacursor(formatter=formatter, hover=True)
plt.show()
```

**Comment by dnth** [comment]
Hi, 
I am aware of the examples, but i cant seem to understand them well. 
In details, I have a bar chart with height that represents number of people that attends an event. But once I hover over the bars, I want a list the names of people that attended the event to pop up. 
Is this doable?

**Comment by joferkington** [comment]
@dnth - Ah, sorry, I misread what you were asking.

It's certainly possible, and you'd use a custom formatter function either way.  However, you'll need a way to associate your list of names with what's plotted.

If we were plotting with `plot`, `scatter`, or several other methods we could use the `ind` passed in to the formatter function to map which bar we're over back to the list of names.  However, the rectangles that `bar` plots don't internally record that they're part of a larger collection, so they can't supply the `ind` kwarg.  Therefore, we'll have to do it based on the x-coordinate of our bars.

As an example (note that this assumes `align='center'`. You'll need to adjust the logic in `formatter` slightly if you're not centering the bars):

```
import numpy as np
import matplotlib.pyplot as plt
from mpldatacursor import datacursor

attendance = [['Frank', 'Jim', 'Anne'],
              ['Mary Ellen', 'Callie', 'Chris'],
              ['Janet', 'Chloe', 'Claire', 'Lisa', 'Charlie', 'Frank', 'Jim'],
              ['James', 'Anne']]
x = range(len(attendance))
y = [len(item) for item in attendance]

fig, ax = plt.subplots()
ax.bar(x, y, align='center', color='lightblue')
ax.margins(0.05)
ax.set_ylim(bottom=0)

# Using a closure to access data. Ideally you'd use a "functor"-style class.
def formatter(**kwargs):
    dist = abs(np.array(x) - kwargs['x'])
    i = dist.argmin()
    return '\n'.join(attendance[i])

datacursor(hover=True, formatter=formatter)
plt.show()
```


```
data = 


```

**Comment by dnth** [comment]
Thank you very much!
