### ISSUE TITLE
multiple mode has lost some features

### ISSUE THREAD

**Issue by Joe-Chapman** [joferkington/mpldatacursor#49]
Hi Joe,

Somewhere along the way, something has changed where now I cannot delete individual cursors with a right-click anymore. I'm using:
mpldatacursor: 0.6.1
anaconda2 32-bit: 2.4.1
ipython 4.0.1
mpl: 1.5.0
backend: QtAgg
ubuntu-mate

Thanks,
Joe

**Comment by joferkington** [comment]
Sorry for my delay in replying! Thanks a bunch for noticing that!

Fixed in ff2c3349ff5d12ddbeb10f7f7def06bc1e2f95c5

**Comment by Joe-Chapman** [comment]
Hi Joe,

Thanks! Just curious, when do plan to reflect the change in pip?

Thanks,
Joe
