### ISSUE TITLE
How to programmatically hide annotations?

### ISSUE THREAD

**Issue by MrSniffer** [joferkington/mpldatacursor#51]
Pressing the 'd' key hides annotations. I don't see a way to do this straightforwardly (e.g. w/o simulating a keypress), such as: datacursor(hide=True)

**Comment by joferkington** [comment]
Typically, it's easiest to call the [`hide` method ](https://github.com/joferkington/mpldatacursor/blob/master/mpldatacursor/datacursor.py#L489)of the `DataCursor` instance.  `hide` will make all annotations created/managed by the `DataCursor` invisible.

E.g.

    dc = datacursor()
    # Interact with the gui...
    dc.hide()

Note that right-clicking on an annotation will hide a specific annotation, as well.  If you'd like to do that programmatically, there's a private `DataCursor._hide_box(annotation_artist)` method.  However, it just does `annotation_artist.set(visible=False)`, there's no real need to use `_hide_box`.

Hope that helps!
