### ISSUE TITLE
Change arrowprops to use shrinkB=0 by default

### ISSUE THREAD

**Issue by anntzer** [joferkington/mpldatacursor#54]
I think that having the arrow head actually touching the annotated point makes things easier to read.  This can be accomplished by setting `shrinkB=0` in `DataCursor.default_annotation_kwargs["arrowprops"]`.

As a side note, `rad=0` can be removed in the same dict as this is set by default by `arc3`.

**Comment by joferkington** [comment]
Good point. Particularly for plots with dense data, having the arrow actually touch the artist definitely adds clarity.
