### ISSUE TITLE
clicks from one figure "leak" into other figures

### ISSUE THREAD

**Issue by anntzer** [joferkington/mpldatacursor#56]
```
from matplotlib import pyplot as plt
from mpldatacursor import datacursor

plt.plot([1, 2])
plt.figure()
plt.plot([1, 2])
datacursor()
plt.show()
```
Clicking on the line in one figure also creates/updates the cursor on the other figure.

Python 3.5.1, matplotlib 1.5.1, tested Qt4, Qt5 and Tk backends.

**Comment by tacaswell** [comment]
Does datacursor attach it self to all active canvases?

**Comment by anntzer** [comment]
If no artists are specified, then I think the answer is yes: https://github.com/joferkington/mpldatacursor/blob/master/mpldatacursor/convenience.py#L154
