### ISSUE TITLE
Feature Request: use left and right arrow keys to move the data cursor

### ISSUE THREAD

**Issue by NoAnyLove** [joferkington/mpldatacursor#59]
Hi Joe,

I think it's more convenient if we can move the data cursor with the left/right arrow keys, just as Matlab does. Sometimes we want to move the data cursor on a very precise point. Using mouse to click is not that precise, and may click at a point around where we want. If we can use the keyboard arrow keys to adjust the data cursor, it would be very convenient.

**Comment by tacaswell** [comment]
This will be a bit tricky as upstream ships with a default binding of the arrow keys to forward and back in view history.

It should be possible to unbind them by simply changing the values of `mpl.rcParams['keymap.forward']` and `mpl.rcParams['keymap.back']` to not include 'left' and 'right'.

**Comment by anntzer** [comment]
You could e.g. default to using ctrl-left/ctrl-right.
A more tricky question, IMO, is what to do when there are multiple annotations simultaneously being on.  I guess you need to define an "active" annotation and have it be the only one being displaced?
Also, the whole thing probably only makes sense once #45 is fixed (and only for snapped annotations, then).

**Comment by joferkington** [comment]
The bigger problem is actually getting the "next" and "previous" data coordinates for arbitrary artists.  It would be nice to support things like bar plots, etc, but that's actually quite difficult, as the individual rectangle doesn't know it's part of the the collection.

At any rate, https://github.com/joferkington/mpldatacursor/commit/6eeec8d30b7227f7049c1a1a36f4d3268068eab5 has an implementation that works for `Line2D`s and most collections.  It binds things to `shift + right` and `shift + left`.  (Personally, I have `ctrl + right`, etc set up as a global keyboard shortcut to switch workspaces, while `shift + left` is usually next word, and therefore usually not bound to a global shortcut.)

**Comment by anntzer** [comment]
There's a tiny issue with this implementation, which is that pressing "shift-left" right after creating an annotation that is interpolated between two data points moves it back by one-and-a-half data points.  Not sure if it's worth fixing but that would probably involve figuring out from the projection function which segment the projection is actually on.
