### ISSUE TITLE
In multiple display mode, removed annotations should be deleted from the DataCursor.annotations dictionary

### ISSUE THREAD

**Issue by anntzer** [joferkington/mpldatacursor#61]
All's in the title.  This should make interactive selection of multiple data points easier.

**Comment by anntzer** [comment]
I was thinking that this would just imply deleting the annotations rather than setting their visibility to False, but I see that you have
```
        # In case it's been hidden earlier...
        annotation.set_visible(True)
```
in `DataCursor.update`.  When can it happen that an annotation is brought back to being visible?

**Comment by joferkington** [comment]
First off, good point.  In multiple display mode, a new annotation is created for every click.  There's no reason to let them pile up in `DataCursor.annotations`.  They're now removed in b8c3e39.  Thanks for the catch!

That particular comment reflects how the non-multiple display options work.  Basically, in the cases of `display="one-per-axes"` or `display="single"`, there's always (and only) one annotation artist per axes.  It's made during initialization, and if it's hidden by right-clicking, it will be made visible again on the next click.

However, there's an additional wrinkle.  Originally, I'd planned for there to be a mechanism to temporarily hide all datacursors and then re-display them.  It's often useful to temporarily hide the datacursors while looking at the data and then toggle them back on.

The hiding portion is there (`DataCursor.hide`), but I never added its compliment.  In fact, I'd forgotten about that entirely until you opened this issue.  I'll be adding that feature shortly.  Thanks for inadvertently reminding me! :)

**Comment by anntzer** [comment]
Actually this fix created another issue (checked by bisecting): deleting (by right-click) an annotation in multiple mode now throws
```
Traceback (most recent call last):
  File "/home/antony/.local/lib/python3.5/site-packages/matplotlib/backends/backend_qt5.py", line 259, in mousePressEvent
    guiEvent=event)
  File "/home/antony/.local/lib/python3.5/site-packages/matplotlib/backend_bases.py", line 1903, in button_press_event
    self.callbacks.process(s, mouseevent)
  File "/home/antony/.local/lib/python3.5/site-packages/matplotlib/cbook.py", line 563, in process
    proxy(*args, **kwargs)
  File "/home/antony/.local/lib/python3.5/site-packages/matplotlib/cbook.py", line 430, in __call__
    return mtd(*args, **kwargs)
  File "/home/antony/src/mpldatacursor/mpldatacursor/datacursor.py", line 623, in _select
    for anno in self.annotations.values():
RuntimeError: dictionary changed size during iteration
```

**Comment by joferkington** [comment]
@anntzer  - Good catch, thanks!  As you have probably noticed, I still tend to use 2.7 on a day-to-day basis, so I miss a lot of Py3 issues at first.
