### ISSUE TITLE
`tolerance` has no effect

### ISSUE THREAD

**Issue by anntzer** [joferkington/mpldatacursor#66]
The `tolerance` kwarg has no effect (as of master).  Test e.g. by setting `tolerance` to 2000 (some very large value) in `scatter_example.py`.

I guess the correct way to do this is to rely on the `pickradius` attribute of the various artists directly (if they support it); if a `tolerance` is passed perhaps it should just modify all the pickradii.

**Comment by joferkington** [comment]
Yeah, that's a result of an upstream change awhile back.  The tolerance used to be set through `set_picker` and it's not anymore.  I noticed at one point, but forgot about it shortly thereafter.  Thanks a ton for catching this and reporting it!

**Comment by joferkington** [comment]
Apparently, I introduced this bug in https://github.com/joferkington/mpldatacursor/commit/017db86a2ce04868e65e76de250c667224f2653d

I'll have to add another workaround, as there are still supported versions of MPL that set the pick radius through `set_picker` instead of `set_pickradius`.
