### ISSUE TITLE
Parameter to display real values for axis with exponents or offsets

### ISSUE THREAD

**Issue by lovehina13** [joferkington/mpldatacursor#75]
![cursor](https://cloud.githubusercontent.com/assets/16979618/20759975/dc25441a-b71e-11e6-8620-a0dfbcbd9f8a.png)

Hello,

I'm using the MplDataCursor library with MatPlotLib.
I have a problem when I'm trying to add a cursor based on plot with exponent axis.
My axis bounds are 10000000 and 12000000, so MatPlotLib displays them like 1.0 and 1.2 with an 1e7 exponent.
However the cursor displays its values like 1.1 and 1.1 but without the exponent.

Could you add some True/False parameter which displays like 11000000 or 1.1 * 1e7 depending on its values? Is this option already available?

Thanks.

**Comment by tacaswell** [comment]
The formatter knows about the offset, you _should_ be able to just ask the formatter for it.

**Comment by lovehina13** [comment]
Right, I found the settings.
(Time to close the issue)
