### ISSUE TITLE
convenience.py:160: MatplotlibDeprecationWarning: and  datacursor.py:140: MatplotlibDeprecationWarning:

### ISSUE THREAD

**Issue by nilswagner** [joferkington/mpldatacursor#92]
The iterable function was deprecated in Matplotlib 3.1 and will be removed in 3.3. Use np.iterable instead.
  if not cbook.iterable(axes):

datacursor.py:140: MatplotlibDeprecationWarning: 
The iterable function was deprecated in Matplotlib 3.1 and will be removed in 3.3. Use np.iterable instead.
  if not cbook.iterable(artists):

**Comment by joferkington** [comment]
Fixed in https://github.com/joferkington/mpldatacursor/pull/93  (Thanks @nilswagner!)
